variables:
  LIBRARY_REPO_URL: https://gitlab.moser.mywire.org/moser/mml.git

before_script:
  - mkdir mml
  - git clone $LIBRARY_REPO_URL
  - cd mml
  - make -j9
  - cd ../

build-job:
  stage: build
  script:
    - make -j9 LIBRARY="-L ./ -L ./mml/" MINCLUDE="-I include -I include/mml-math -I mml/include/"
  artifacts:
    paths:
      - "lib/"

test-calc:
  stage: test
  needs:
    - build-job
  dependencies:
    - build-job
  script:
    - cd test
    - make SRC=calc.cpp INCLUDE="-I ../include -I ../mml/include/" LIBRARY="-L ../lib -L ../mml/lib/"
    - ./calc.x

test-sh-ya-algo:
  stage: test
  needs:
    - build-job
  dependencies:
    - build-job
  script:
    - cd test
    - make SRC=sh-ya-algo.cpp INCLUDE="-I ../include -I ../mml/include/" LIBRARY="-L ../lib -L ../mml/lib/"
    - ./sh-ya-algo.x

test-matrix:
  stage: test
  needs:
    - build-job
  #dependencies:
  #  - build-job
  script:
    - cd test
    - make SRC=matrix.cpp INCLUDE="-I ../include -I ../mml/include/" LIBRARY="-L ../lib -L ../mml/lib/"
    - ./matrix.x

deploy-prod:
  stage: deploy
  script:
    - cd calculator
    - make INCLUDE="-I ../include -I ../mml/include/" LIBRARY="-L ../lib -L ../mml/lib/"
  dependencies:
    - build-job
  environment: production
