stages:
  - build
  - test
#  - deploy


variables:
  LIBRARY_REPO_URL: https://gitlab.moser.mywire.org/moser/mml.git

before_script:
  - cd ../
  - rm -rf mml
  - mkdir mml
  - git clone $LIBRARY_REPO_URL
  - cd mml
  - mkdir build
  - cd build
  - cmake ..
  - make -j5
  - cd ../../mml-math

build-job:
  stage: build
  script:
    - ls mml/build
    - mkdir build
    - cd build
    - CLEANED_PATH=$(echo "$PWD" | sed 's/mml-math//')
    - cmake -DMML_LIBPATH=${CLEANED_PATH}/mml/build/ -DMML_INCPATH=${CLEANED_PATH}/mml/include ..
    - make -j5
  artifacts:
    paths:
      - "build/"
      - "mml/"

test:
  stage: test
  needs:
    - build-job
  script:
    - cd build
    - make test

