stages:
  - build
  - test
#  - deploy


variables:
  LIBRARY_REPO_URL: https://gitlab.moser.mywire.org/moser/mml.git
  LIB: ${PWD}

before_script:
  - mkdir mml
  - git clone $LIBRARY_REPO_URL
  - cd mml
  - mkdir build
  - cd build
  - cmake ..
  - make -j5
  - cd ../../

build-job:
  stage: build
  script:
    - echo $LIB
    - echo $PWD
    - ls mml/build
    - mkdir build
    - cd build
    - cmake .. -DMML_LIBPATH=../mml/build/ -DMML_INCPATH=../mml/include
    - make -j5
  artifacts:
    paths:
      - "build/"
      - "mml/"

test:
  stage: test
  needs:
    - build-job
  script:
    - cd build
    - make test

